name: build

on: workflow_dispatch

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push v1.19
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          build-args: NGINX_VERSION=1.19.7
          tags: |
            flrnrud7/laravel-nginx:latest
            flrnrud7/laravel-nginx:1.19
            flrnrud7/laravel-nginx:1.19.7
            flrnrud7/laravel-nginx:mainline
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: flrnrud7/laravel-nginx
